### ISSUE TITLE
when I run 'sudo pip install beanstalkc',sth wrong.

### ISSUE THREAD

**Issue by fst034356** [earl/beanstalkc#68]
```
Collecting beanstalkc
  Using cached beanstalkc-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ubj0ksew/beanstalkc/setup.py", line 5, in <module>
        from beanstalkc import __version__ as src_version
      File "/tmp/pip-build-ubj0ksew/beanstalkc/beanstalkc.py", line 42
        except socket.error, err:
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ubj0ksew/beanstalkc/
```

can u help me?

**Comment by svisser** [comment]
@fst034356 that syntax isn't valid in Python 3.

This project is not yet compatible with Python 3.

**Comment by fst034356** [comment]
oh i see,thx
