### ISSUE TITLE
Does not work with Python 3.9

### ISSUE THREAD

**Issue by pavel-kolesnikov** [earl/beanstalkc#77]
After installing with 
```
pip install --user beanstalkc
```

Trying this will fails:
```
~> python
Python 3.9.5 (default, May 14 2021, 00:00:00) 
[GCC 11.1.1 20210428 (Red Hat 11.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import beanstalkc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/beanstalkc.py", line 78
    except CommandFailed, (status, results):
                        ^
SyntaxError: invalid syntax
```

**Comment by reedzhao** [comment]
I am running into the same problem.  Is there an alternative beanstalk client?

**Comment by reedzhao** [comment]
https://github.com/seveas/beanstalkc

conda install -c bjrn beanstalkc3
